using SshKeySetupTool.Domain;

namespace SshKeySetupTool.Presentation;

public enum UiLanguage
{
    Chinese,
    English
}

public sealed record UiText(
    string LanguageChoice,
    string Title,
    string Host,
    string Port,
    string Username,
    string Password,
    string PrivateKeyPath,
    string Status,
    string ConnectionDetails,
    string GenerateAndInstall,
    string Ready,
    string Working,
    string CompletedCopied,
    string CompletedNotCopied,
    string Cancelled,
    string FailedPrefix,
    string ConfirmServerTitle,
    string ConfirmServerMessageFormat,
    string ConfirmServerConfigurationTitle,
    string ConfirmServerConfigurationMessageFormat,
    string CheckingServerConfiguration,
    string WaitingForServerConfigurationConsent,
    string EnablingServerConfiguration,
    string InstallingPublicKey,
    string VerifyingPrivateKey,
    string RollingBackServerConfiguration,
    string CheckingOpenSsh,
    string OpenSshInstalled,
    string InstallOpenSsh,
    string OpenSshCheckFailed,
    string OpenSshInstallFailed,
    string OpenSshInstallCancelled,
    string BrowsePrivateKeyPath,
    string GenerationHistory,
    string ClearHistory,
    string ClearHistoryConfirmation,
    string HistoryClearFailed,
    string HistoryEmpty,
    string HistoryTime,
    string HistoryHost,
    string HistoryPort,
    string HistoryUsername,
    string HistoryPrivateKeyPath,
    string HistoryResult,
    string HistorySucceeded,
    string HistoryFailed,
    string HistoryCancelled)
{
    public string FailureLabel(SetupFailureKind kind) => kind switch
    {
        SetupFailureKind.ServerConfigurationInspection =>
            LanguageChoice == "EN" ? "Server SSH configuration check failed" : "服务器 SSH 配置检测失败",
        SetupFailureKind.ServerConfigurationRootRequired =>
            LanguageChoice == "EN" ? "Automatic repair requires the root account" : "自动修复需要 root 账号",
        SetupFailureKind.ServerConfigurationDeclined =>
            LanguageChoice == "EN" ? "Server SSH repair was cancelled" : "服务器 SSH 修复已取消",
        SetupFailureKind.ServerConfigurationApply =>
            LanguageChoice == "EN" ? "Server SSH configuration repair failed" : "服务器 SSH 配置修复失败",
        SetupFailureKind.PublicKeyInstallation =>
            LanguageChoice == "EN" ? "Public-key installation failed" : "公钥写入失败",
        SetupFailureKind.PrivateKeyVerification =>
            LanguageChoice == "EN" ? "Private-key verification failed" : "私钥验证失败",
        SetupFailureKind.Rollback =>
            LanguageChoice == "EN"
                ? "SSH configuration rollback failed; manual recovery may be required"
                : "SSH 配置回滚失败，可能需要手动恢复",
        _ => FailedPrefix.TrimEnd()
    };
}

public static class UiTextCatalog
{
    public static UiText For(UiLanguage language) => language == UiLanguage.English
        ? new UiText(
            "EN",
            "SSHKEY   //   SSH Key Setup",
            "Server IP",
            "Port",
            "Username",
            "Password",
            "Private key path",
            "Status",
            "Codex connection details",
            "Generate and Install",
            "Ready.",
            "Generating the local key and connecting to the server...",
            "Complete. Codex connection details are shown below and copied to the clipboard.",
            "Complete. Codex connection details are shown below; please copy them manually.",
            "Operation cancelled.",
            "Failed: ",
            "Confirm server",
            "First connection to server {0}.\r\n\r\nServer SHA-256 key fingerprint:\r\n{1}\r\n\r\nTrust this server for this operation only?",
            "Enable SSH public-key authentication",
            "SSHKEY detected PubkeyAuthentication no on server {0}.\r\n\r\nDetected setting: {1}\r\n\r\nSSHKEY will validate the SSH configuration and reload SSH. Password login will not be disabled. If setup fails, the change will be rolled back.\r\n\r\nContinue?",
            "Checking server SSH configuration...",
            "Waiting for confirmation to repair server SSH...",
            "Enabling server SSH public-key authentication...",
            "Installing the public key...",
            "Verifying the private key...",
            "Rolling back server SSH configuration...",
            "Checking OpenSSH…",
            "✓ OpenSSH installed",
            "Install OpenSSH",
            "OpenSSH check failed",
            "OpenSSH installation failed — retry",
            "OpenSSH installation was cancelled — retry",
            "Browse...",
            "Generation history",
            "Clear history",
            "Clear all generation history?",
            "Unable to clear generation history.",
            "No generation history yet.",
            "Time",
            "Server",
            "Port",
            "Username",
            "Private key path",
            "Result",
            "Succeeded",
            "Failed",
            "Cancelled" )
        : new UiText(
            "中文",
            "SSHKEY   //   SSH密钥设置",
            "服务器 IP",
            "端口",
            "账号",
            "密码",
            "私钥路径",
            "状态",
            "Codex 连接信息",
            "生成并写入服务器",
            "准备就绪。",
            "正在生成本地密钥并连接服务器...",
            "完成，Codex 连接信息已显示在下方并复制到剪贴板。",
            "完成，Codex 连接信息已显示在下方，请手动复制。",
            "操作已取消。",
            "失败：",
            "确认服务器",
            "首次连接服务器 {0}。\r\n\r\n服务器 SHA-256 密钥指纹：\r\n{1}\r\n\r\n是否仅在本次操作中信任此服务器？",
            "启用 SSH 公钥认证",
            "SSHKEY 检测到服务器 {0} 的 PubkeyAuthentication no。\r\n\r\n检测到的设置：{1}\r\n\r\nSSHKEY 将验证 SSH 配置并重新加载 SSH，不会禁用密码登录。如果设置失败，将回滚配置。\r\n\r\n是否继续？",
            "正在检查服务器 SSH 配置...",
            "等待确认修复服务器 SSH...",
            "正在启用服务器 SSH 公钥认证...",
            "正在写入公钥...",
            "正在验证私钥...",
            "正在回滚服务器 SSH 配置...",
            "检测 OpenSSH…",
            "✓ OpenSSH 已安装",
            "一键安装 OpenSSH",
            "OpenSSH 检测失败",
            "OpenSSH 安装失败，请重试",
            "OpenSSH 安装已取消，请重试",
            "浏览...",
            "生成历史",
            "清空历史",
            "确定清空全部生成历史吗？",
            "无法清空生成历史。",
            "暂无生成历史。",
            "时间",
            "服务器",
            "端口",
            "账号",
            "私钥路径",
            "结果",
            "成功",
            "失败",
            "已取消");
}
